name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            artifact: main
          - branch: ${{ github.head_ref }}
            artifact: pull-request

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run test

    - name: "Upload Coverage"
      uses: actions/upload-artifact@v4
      with:
          name: coverage-${{ matrix.artifact }}
          path: coverage

    # テストは通るがビルドで落ちるケースがあるため、ビルドできるかの確認も追加
    - name: Build
      run: npm run build
