/* tslint:disable */
/* eslint-disable */
/**
 * Promptis Usage API
 * このAPIはPromptisの利用状況を収集するためのAPIです 
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * Contact: gai_dev_standard@ml.tis.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

